-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 18:50:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ris_projectdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ris_projectdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ris_projectdatabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ris_projectdatabase` ;

-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Uloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Uloga` (
  `idUloga` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUloga`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Korisnik` (
  `username` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `Uloga_idUloga` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_Korisnik_Uloga_idx` (`Uloga_idUloga` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_Uloga`
    FOREIGN KEY (`Uloga_idUloga`)
    REFERENCES `ris_projectdatabase`.`Uloga` (`idUloga`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Kartica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Kartica` (
  `Korisnik_username` VARCHAR(45) NOT NULL,
  `brojKartice` INT NOT NULL,
  `datumIsticanja` DATE NOT NULL,
  `CVV` INT NOT NULL,
  PRIMARY KEY (`brojKartice`, `datumIsticanja`, `CVV`, `Korisnik_username`),
  INDEX `fk_Kartica_Korisnik1_idx` (`Korisnik_username` ASC) VISIBLE,
  CONSTRAINT `fk_Kartica_Korisnik1`
    FOREIGN KEY (`Korisnik_username`)
    REFERENCES `ris_projectdatabase`.`Korisnik` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Kategorija` (
  `idKategorija` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKategorija`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`KategorijeKorisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`KategorijeKorisnika` (
  `idKategorijeKorisnika` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKategorijeKorisnika`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Popust`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Popust` (
  `idPopust` INT NOT NULL AUTO_INCREMENT,
  `procenat` DECIMAL(5,2) NOT NULL,
  `datumIsticanja` DATE NOT NULL,
  PRIMARY KEY (`idPopust`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Proizvodjac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Proizvodjac` (
  `idProizvodjac` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProizvodjac`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Proizvod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Proizvod` (
  `idProizvod` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  `slika` LONGBLOB NOT NULL,
  `opis` VARCHAR(500) NOT NULL,
  `Kategorija_idKategorija` INT NOT NULL,
  `Proizvodjac_idProizvodjac` INT NOT NULL,
  `Popust_idPopust` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProizvod`),
  INDEX `fk_Proizvod_Kategorija1_idx` (`Kategorija_idKategorija` ASC) VISIBLE,
  INDEX `fk_Proizvod_Proizvodjac1_idx` (`Proizvodjac_idProizvodjac` ASC) VISIBLE,
  INDEX `fk_Proizvod_Popust1_idx` (`Popust_idPopust` ASC) VISIBLE,
  CONSTRAINT `fk_Proizvod_Kategorija1`
    FOREIGN KEY (`Kategorija_idKategorija`)
    REFERENCES `ris_projectdatabase`.`Kategorija` (`idKategorija`),
  CONSTRAINT `fk_Proizvod_Popust1`
    FOREIGN KEY (`Popust_idPopust`)
    REFERENCES `ris_projectdatabase`.`Popust` (`idPopust`),
  CONSTRAINT `fk_Proizvod_Proizvodjac1`
    FOREIGN KEY (`Proizvodjac_idProizvodjac`)
    REFERENCES `ris_projectdatabase`.`Proizvodjac` (`idProizvodjac`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Ocena` (
  `Korisnik_username` VARCHAR(45) NOT NULL,
  `Proizvod_idProizvod` INT NOT NULL,
  `ocena` INT NOT NULL,
  PRIMARY KEY (`Korisnik_username`, `Proizvod_idProizvod`),
  INDEX `fk_Korisnik_has_Proizvod1_Proizvod1_idx` (`Proizvod_idProizvod` ASC) VISIBLE,
  INDEX `fk_Ocena_Korisnik1_idx` (`Korisnik_username` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_has_Proizvod1_Proizvod1`
    FOREIGN KEY (`Proizvod_idProizvod`)
    REFERENCES `ris_projectdatabase`.`Proizvod` (`idProizvod`),
  CONSTRAINT `fk_Ocena_Korisnik1`
    FOREIGN KEY (`Korisnik_username`)
    REFERENCES `ris_projectdatabase`.`Korisnik` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Omiljeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Omiljeno` (
  `Korisnik_username` VARCHAR(45) NOT NULL,
  `Proizvod_idProizvod` INT NOT NULL,
  `KategorijeKorisnika_idKategorijeKorisnika` INT NOT NULL,
  PRIMARY KEY (`Korisnik_username`, `Proizvod_idProizvod`),
  INDEX `fk_Korisnik_has_Proizvod_Proizvod1_idx` (`Proizvod_idProizvod` ASC) VISIBLE,
  INDEX `fk_Omiljeno_KategorijeKorisnika1_idx` (`KategorijeKorisnika_idKategorijeKorisnika` ASC) VISIBLE,
  INDEX `fk_Omiljeno_Korisnik1_idx` (`Korisnik_username` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_has_Proizvod_Proizvod1`
    FOREIGN KEY (`Proizvod_idProizvod`)
    REFERENCES `ris_projectdatabase`.`Proizvod` (`idProizvod`),
  CONSTRAINT `fk_Omiljeno_KategorijeKorisnika1`
    FOREIGN KEY (`KategorijeKorisnika_idKategorijeKorisnika`)
    REFERENCES `ris_projectdatabase`.`KategorijeKorisnika` (`idKategorijeKorisnika`),
  CONSTRAINT `fk_Omiljeno_Korisnik1`
    FOREIGN KEY (`Korisnik_username`)
    REFERENCES `ris_projectdatabase`.`Korisnik` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Porudzbina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Porudzbina` (
  `korisnik_username` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `datumNarucivanja` DATE NOT NULL,
  `datumIsporuke` DATE NOT NULL,
  INDEX `fk_Porudzbina_korisnik_idx` (`korisnik_username` ASC) VISIBLE,
  PRIMARY KEY (`korisnik_username`),
  CONSTRAINT `fk_Porudzbina_korisnik`
    FOREIGN KEY (`korisnik_username`)
    REFERENCES `ris_projectdatabase`.`Korisnik` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris_projectdatabase`.`Porudzbina_has_Proizvod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris_projectdatabase`.`Porudzbina_has_Proizvod` (
  `Porudzbina_korisnik_username` VARCHAR(45) NOT NULL,
  `proizvod_idProizvod` INT NOT NULL,
  PRIMARY KEY (`Porudzbina_korisnik_username`, `proizvod_idProizvod`),
  INDEX `fk_Porudzbina_has_proizvod_proizvod1_idx` (`proizvod_idProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_Porudzbina_has_proizvod_Porudzbina1`
    FOREIGN KEY (`Porudzbina_korisnik_username`)
    REFERENCES `ris_projectdatabase`.`Porudzbina` (`korisnik_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Porudzbina_has_proizvod_proizvod1`
    FOREIGN KEY (`proizvod_idProizvod`)
    REFERENCES `ris_projectdatabase`.`Proizvod` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
